version: "3.8"
services:

  random-search:
    build: .
    stop_signal: SIGINT
    ports:
      - "8080:80"
    volumes:
      - "//var/run/docker.sock:/var/run/docker.sock"
      # - "./db.json:/app/db.json"
    environment:
      NUM_WORKERS: 4
      BUILD_CONTEXT: "./example-target"
      PARAMS: |
        N_LAYERS: [1, 2, 3]
        LAYER_SIZE: [16, 32, 64]
        ACTIVATION: ["tanh", "relu"]
        LR: [1e-2, 1e-3, 1e-4]
